# TCL File Generated by Component Editor 18.1
# Thu Feb 20 11:48:16 CET 2025
# DO NOT MODIFY


# 
# MultiBusMemoryController "HyperBUS/xSPI Interface" v1.0
# MicroFPGA UGh 2025.02.20.11:48:16
# HyperBUS/xSPI Interface
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module MultiBusMemoryController
# 
set_module_property DESCRIPTION "HyperBUS/xSPI Interface"
set_module_property NAME openmbmc_memory_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Memories and Memory Controllers"
set_module_property AUTHOR "MicroFPGA UGh"
set_module_property DISPLAY_NAME "HyperBUS/xSPI Interface"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL openmbmc
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file openmbmc.v VERILOG PATH openmbmc.v TOP_LEVEL_FILE
add_fileset_file openmbmc_platform.v VERILOG PATH openmbmc_platform.v


# 
# documentation links
# 
add_documentation_link "Github Repository" https://github.com/micro-FPGA/OpenMBMC
add_documentation_link Documentation https://github.com/micro-FPGA/OpenMBMC/tree/main/doc
add_documentation_link "Support Issues" https://github.com/micro-FPGA/OpenMBMC/issues


# 
# parameters
# 
add_parameter G_ADDRBITS INTEGER 23 "Number of Address bits"
set_parameter_property G_ADDRBITS DEFAULT_VALUE 23
set_parameter_property G_ADDRBITS DISPLAY_NAME G_ADDRBITS
set_parameter_property G_ADDRBITS WIDTH ""
set_parameter_property G_ADDRBITS TYPE INTEGER
set_parameter_property G_ADDRBITS UNITS None
set_parameter_property G_ADDRBITS ALLOWED_RANGES 22:26
set_parameter_property G_ADDRBITS DESCRIPTION "Number of Address bits"
set_parameter_property G_ADDRBITS HDL_PARAMETER true
add_parameter G_DEVICE INTEGER 0 "Device Type"
set_parameter_property G_DEVICE DEFAULT_VALUE 0
set_parameter_property G_DEVICE DISPLAY_NAME G_DEVICE
set_parameter_property G_DEVICE WIDTH ""
set_parameter_property G_DEVICE TYPE INTEGER
set_parameter_property G_DEVICE UNITS None
set_parameter_property G_DEVICE ALLOWED_RANGES 0:1
set_parameter_property G_DEVICE DESCRIPTION "Device Type"
set_parameter_property G_DEVICE HDL_PARAMETER true
add_parameter G_VARLAT BOOLEAN true "Variable Latency"
set_parameter_property G_VARLAT DEFAULT_VALUE true
set_parameter_property G_VARLAT DISPLAY_NAME G_VARLAT
set_parameter_property G_VARLAT WIDTH ""
set_parameter_property G_VARLAT TYPE BOOLEAN
set_parameter_property G_VARLAT UNITS None
set_parameter_property G_VARLAT DESCRIPTION "Variable Latency"
set_parameter_property G_VARLAT HDL_PARAMETER true
add_parameter G_DDP BOOLEAN false "Dual Die Package"
set_parameter_property G_DDP DEFAULT_VALUE false
set_parameter_property G_DDP DISPLAY_NAME G_DDP
set_parameter_property G_DDP WIDTH ""
set_parameter_property G_DDP TYPE BOOLEAN
set_parameter_property G_DDP UNITS None
set_parameter_property G_DDP DESCRIPTION "Dual Die Package"
set_parameter_property G_DDP HDL_PARAMETER true
add_parameter G_TVCS INTEGER 15000 "Tvcs parameter"
set_parameter_property G_TVCS DEFAULT_VALUE 15000
set_parameter_property G_TVCS DISPLAY_NAME G_TVCS
set_parameter_property G_TVCS TYPE INTEGER
set_parameter_property G_TVCS UNITS None
set_parameter_property G_TVCS ALLOWED_RANGES 5000:30000
set_parameter_property G_TVCS DESCRIPTION "Tvcs parameter"
set_parameter_property G_TVCS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock avl_clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_rst reset Input 1


# 
# connection point avl_mem
# 
add_interface avl_mem avalon end
set_interface_property avl_mem addressUnits WORDS
set_interface_property avl_mem associatedClock avl_clock
set_interface_property avl_mem associatedReset reset
set_interface_property avl_mem bitsPerSymbol 8
set_interface_property avl_mem bridgedAddressOffset 0
set_interface_property avl_mem burstOnBurstBoundariesOnly false
set_interface_property avl_mem burstcountUnits WORDS
set_interface_property avl_mem explicitAddressSpan 0
set_interface_property avl_mem holdTime 0
set_interface_property avl_mem isMemoryDevice true
set_interface_property avl_mem linewrapBursts false
set_interface_property avl_mem maximumPendingReadTransactions 0
set_interface_property avl_mem maximumPendingWriteTransactions 0
set_interface_property avl_mem readLatency 0
set_interface_property avl_mem readWaitTime 1
set_interface_property avl_mem setupTime 0
set_interface_property avl_mem timingUnits Cycles
set_interface_property avl_mem writeWaitTime 0
set_interface_property avl_mem ENABLED true
set_interface_property avl_mem EXPORT_OF ""
set_interface_property avl_mem PORT_NAME_MAP ""
set_interface_property avl_mem CMSIS_SVD_VARIABLES ""
set_interface_property avl_mem SVD_ADDRESS_GROUP ""

add_interface_port avl_mem avl_mem_address address Input "(G_ADDRBITS-3) - (0) + 1"
add_interface_port avl_mem avl_mem_read read Input 1
add_interface_port avl_mem avl_mem_readdata readdata Output 32
add_interface_port avl_mem avl_mem_write write Input 1
add_interface_port avl_mem avl_mem_writedata writedata Input 32
add_interface_port avl_mem avl_mem_waitrequest waitrequest Output 1
add_interface_port avl_mem avl_mem_byteenable byteenable Input 4
set_interface_assignment avl_mem embeddedsw.configuration.isFlash 0
set_interface_assignment avl_mem embeddedsw.configuration.isMemoryDevice 1
set_interface_assignment avl_mem embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avl_mem embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avl_clock
# 
add_interface avl_clock clock end
set_interface_property avl_clock clockRate 0
set_interface_property avl_clock ENABLED true
set_interface_property avl_clock EXPORT_OF ""
set_interface_property avl_clock PORT_NAME_MAP ""
set_interface_property avl_clock CMSIS_SVD_VARIABLES ""
set_interface_property avl_clock SVD_ADDRESS_GROUP ""

add_interface_port avl_clock avl_clock clk Input 1


# 
# connection point hyper_clock
# 
add_interface hyper_clock clock end
set_interface_property hyper_clock clockRate 0
set_interface_property hyper_clock ENABLED true
set_interface_property hyper_clock EXPORT_OF ""
set_interface_property hyper_clock PORT_NAME_MAP ""
set_interface_property hyper_clock CMSIS_SVD_VARIABLES ""
set_interface_property hyper_clock SVD_ADDRESS_GROUP ""

add_interface_port hyper_clock hyper_clock clk Input 1


# 
# connection point hyperbus
# 
add_interface hyperbus conduit end
set_interface_property hyperbus associatedClock avl_clock
set_interface_property hyperbus associatedReset ""
set_interface_property hyperbus ENABLED true
set_interface_property hyperbus EXPORT_OF ""
set_interface_property hyperbus PORT_NAME_MAP ""
set_interface_property hyperbus CMSIS_SVD_VARIABLES ""
set_interface_property hyperbus SVD_ADDRESS_GROUP ""

add_interface_port hyperbus cs_n cs_n Output 1
add_interface_port hyperbus ck ck Output 1
add_interface_port hyperbus ck_n ck_n Output 1
add_interface_port hyperbus rwds rwds Bidir 1
add_interface_port hyperbus dq dq Bidir 8
add_interface_port hyperbus reset_n reset_n Output 1


# 
# connection point init_done
# 
add_interface init_done conduit end
set_interface_property init_done associatedClock avl_clock
set_interface_property init_done associatedReset ""
set_interface_property init_done ENABLED true
set_interface_property init_done EXPORT_OF ""
set_interface_property init_done PORT_NAME_MAP ""
set_interface_property init_done CMSIS_SVD_VARIABLES ""
set_interface_property init_done SVD_ADDRESS_GROUP ""

add_interface_port init_done init_done init_done Output 1


# 
# connection point debug
# 
add_interface debug conduit end
set_interface_property debug associatedClock avl_clock
set_interface_property debug associatedReset ""
set_interface_property debug ENABLED true
set_interface_property debug EXPORT_OF ""
set_interface_property debug PORT_NAME_MAP ""
set_interface_property debug CMSIS_SVD_VARIABLES ""
set_interface_property debug SVD_ADDRESS_GROUP ""

add_interface_port debug dq_dbg dq_dbg Output 8
add_interface_port debug rwds_dbg rwds_dbg Output 1
add_interface_port debug state_dbg state_dbg Output 10

